INCLUDE (GV_CMakeCommon)

INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/GigaSpace)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/GsCompute)
INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR}/GsGraphics)

LINK_DIRECTORIES(${LIBRARY_PATH})